import json

from fastapi.testclient import TestClient

from app.main import app


client = TestClient(app)


def sample_payload(**overrides):
    payload = {
        "url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        "title": "AI Documentary: The Future of Cities",
        "channelName": "Future Stories Lab",
        "description": "A cinematic documentary created with AI-assisted visuals and narration.",
        "thumbnailUrl": "https://i.ytimg.com/vi/dQw4w9WgXcQ/hqdefault.jpg",
        "pinnedComment": None,
        "transcript": None,
        "screenshotBase64": "data:image/png;base64,iVBORw0KGgo=",
    }
    payload.update(overrides)
    return payload


def test_audit_video_returns_positioned_mock_report():
    response = client.post("/audit/video", json=sample_payload())

    assert response.status_code == 200
    data = response.json()

    assert data["riskScore"] in [1, 2, 3, 4, 5]
    assert data["riskLabel"] in ["Low", "Medium", "High"]
    assert data["biggestFinding"]
    assert "viewer" in data["quickestFix"]
    assert "AI-assisted" in data["descriptionDisclosure"]
    assert "AI-assisted" in data["pinnedCommentDisclosure"]
    assert "not an AI detection" in data["platformReadinessNote"]
    assert "## DisclosureLens Video Audit" in data["markdown"]
    assert "This video is AI-generated" not in data["markdown"]
    assert "violates" not in data["markdown"].lower()


def test_audit_video_rejects_non_youtube_url():
    response = client.post("/audit/video", json=sample_payload(url="https://example.com/video"))

    assert response.status_code == 422
    assert "YouTube" in response.text


def test_audit_video_handles_missing_optional_fields():
    response = client.post(
        "/audit/video",
        json=sample_payload(
            description=None,
            thumbnailUrl=None,
            pinnedComment=None,
            transcript=None,
            screenshotBase64=None,
        ),
    )

    assert response.status_code == 200
    data = response.json()
    assert data["riskLabel"] == "Medium"
    assert "rerun the audit" in data["quickestFix"]
    assert data["recommendedAction"] == "rerun_with_more_context"
    assert data["showDisclosureTemplates"] is False
    assert data["contextQuality"] == "thin"


def test_audit_video_scores_explicit_disclosure_as_lowest_risk():
    response = client.post(
        "/audit/video",
        json=sample_payload(
            description="Transparency: this video was created with AI-assisted visuals, voice, and editing.",
            pinnedComment="We used AI-assisted tools and human review before publishing.",
        ),
    )

    assert response.status_code == 200
    data = response.json()
    assert data["riskScore"] == 1
    assert data["riskLabel"] == "Low"
    assert "already includes visible AI-use disclosure" in data["biggestFinding"]
    assert data["recommendedAction"] == "improve_existing_disclosure"
    assert data["showDisclosureTemplates"] is True
    assert "creator_disclosure" in data["signalsFound"]


def test_audit_video_scores_strong_undisclosed_ai_signals_as_high_risk():
    response = client.post(
        "/audit/video",
        json=sample_payload(
            title="AI Voice Recreates Lost Celebrity Interview",
            description="Synthetic voice restoration and generated visuals bring the story to life.",
            pinnedComment=None,
        ),
    )

    assert response.status_code == 200
    data = response.json()
    assert data["riskScore"] == 5
    assert data["riskLabel"] == "High"
    assert "Strong visible AI-use signals" in data["biggestFinding"]
    assert data["recommendedAction"] == "add_disclosure"
    assert data["showDisclosureTemplates"] is True
    assert "strong_ai_signal" in data["signalsFound"]


def test_audit_video_recognizes_synthetic_content_disclosure_as_creator_disclosure():
    response = client.post(
        "/audit/video",
        json=sample_payload(
            url="https://www.youtube.com/watch?v=Naq-SkUy6Ho",
            title="[AI-Generated] AI Implementation Demo - AI Visuals & Voice by Cline.bot v3",
            channelName="The AI Coach",
            description=(
                "SYNTHETIC CONTENT DISCLOSURE: This entire video, including both visuals AND voice narration, "
                "is 100% generated by AI using Cline.bot v3.0. No real person's voice or likeness was used "
                "or altered. Introduction (AI narration). Current State of AI Adoption (AI-generated slides)."
            ),
            pinnedComment=None,
        ),
    )

    assert response.status_code == 200
    data = response.json()
    assert data["riskScore"] == 1
    assert data["riskLabel"] == "Low"
    assert "already includes visible AI-use disclosure" in data["biggestFinding"]
    assert data["recommendedAction"] == "improve_existing_disclosure"
    assert data["showDisclosureTemplates"] is True
    assert "creator_disclosure" in data["signalsFound"]
    assert "strong_ai_signal" in data["signalsFound"]


def test_audit_video_recognizes_creator_description_ai_voice_and_generated_visuals_as_disclosure():
    response = client.post(
        "/audit/video",
        json=sample_payload(
            url="https://www.youtube.com/watch?v=UsQArmAbYks",
            title="The Honest Woodcutter 🌳✨ | Classic Moral Story | AI Voice & AI Images",
            channelName="TamEng Spot",
            description=(
                "Enjoy the classic Honest Woodcutter story presented with AI Voice narration and "
                "AI-generated visuals. This timeless story highlights the value of honesty and integrity."
            ),
            pinnedComment=None,
        ),
    )

    assert response.status_code == 200
    data = response.json()
    assert data["riskScore"] == 1
    assert data["riskLabel"] == "Low"
    assert "already includes visible AI-use disclosure" in data["biggestFinding"]
    assert data["recommendedAction"] == "improve_existing_disclosure"
    assert data["showDisclosureTemplates"] is True
    assert "creator_disclosure" in data["signalsFound"]
    assert "strong_ai_signal" in data["signalsFound"]


def test_audit_video_scores_dotted_ai_generated_title_as_signal_even_with_short_description():
    response = client.post(
        "/audit/video",
        json=sample_payload(
            url="https://www.youtube.com/watch?v=16ZN3RBztvo",
            title="A.I. Generated Horror Is SO Disturbing",
            channelName="Joe Bartolozzi",
            description="AzeAlter OG VID: Sharing is Caring || RED RAINBOW.",
            pinnedComment=None,
            transcript=None,
        ),
    )

    assert response.status_code == 200
    data = response.json()
    assert data["riskScore"] == 4
    assert data["riskLabel"] == "Medium"
    assert data["recommendedAction"] == "add_disclosure"
    assert data["showDisclosureTemplates"] is True
    assert "strong_ai_signal" in data["signalsFound"]


def test_audit_video_recognizes_natural_language_ai_clone_disclosure_from_real_page():
    response = client.post(
        "/audit/video",
        json=sample_payload(
            url="https://www.youtube.com/watch?v=m647KpdNTDg",
            title="YouTube’s NEW Rules for AI Videos (How to Make Money Now)",
            channelName="AI creator education channel",
            description=(
                "I cloned myself with AI, created 2 faceless YouTube videos, and made money. "
                "Here's how you can too—and the new YouTube rules you MUST follow. "
                "AI-generated video summary may appear on the page."
            ),
            pinnedComment=None,
        ),
    )

    assert response.status_code == 200
    data = response.json()
    assert data["riskScore"] == 1
    assert data["riskLabel"] == "Low"
    assert data["recommendedAction"] == "improve_existing_disclosure"
    assert data["showDisclosureTemplates"] is True
    assert "creator_disclosure" in data["signalsFound"]
    assert "strong_ai_signal" in data["signalsFound"]
    assert "platform_ai_label" in data["signalsFound"]


def test_audit_video_treats_youtube_auto_dub_label_as_low_risk_platform_context():
    response = client.post(
        "/audit/video",
        json=sample_payload(
            title="Mermaids, Water Spirits & Seduction… What They Really Want",
            channelName="podcast",
            description=(
                "What if the marine kingdom is more than mythology? TAKE THE NEXT STEP. "
                "How this was made Auto-dubbed Audio tracks for some languages were automatically generated. "
                "Learn more. Chapters include Assaulted by a Mermaid and The Sirens of the Deep."
            ),
            pinnedComment=None,
        ),
    )

    assert response.status_code == 200
    data = response.json()
    assert data["riskScore"] == 2
    assert data["riskLabel"] == "Low"
    assert "platform-generated AI labels" in data["biggestFinding"]
    assert "main video itself is AI-generated" in data["biggestFinding"]
    assert data["recommendedAction"] == "none"
    assert data["showDisclosureTemplates"] is False
    assert "platform_ai_label" in data["signalsFound"]
    assert "strong_ai_signal" not in data["signalsFound"]


def test_audit_video_scores_plain_interview_without_ai_signals_as_low_risk():
    response = client.post(
        "/audit/video",
        json=sample_payload(
            url="https://www.youtube.com/watch?v=faMt1TEzh8Q",
            title="“There’s 10 of Them” UFO Super Users Confirmed by DARPA Scientist | Bob McGwier",
            channelName="Danny Jones",
            description=(
                "Watch every episode ad-free & uncensored on Patreon. Dr. Robert McGwier is a PhD applied "
                "mathematician & engineer known for work with CIA, NSA and DARPA in digital signal processing, "
                "software-defined radio & cognitive radio. Chapters include Working for NSA, CIA & FBI, Bob's "
                "two UAP encounters, and Seeing orbs with Chris Bledsoe."
            ),
            pinnedComment=None,
        ),
    )

    assert response.status_code == 200
    data = response.json()
    assert data["riskScore"] == 1
    assert data["riskLabel"] == "Low"
    assert "No visible AI-use signals" in data["biggestFinding"]
    assert "No disclosure fix is recommended" in data["quickestFix"]
    assert data["recommendedAction"] == "none"
    assert data["showDisclosureTemplates"] is False
    assert data["signalsFound"] == []
    assert data["contextQuality"] == "meaningful"
    assert "description" in data["evidenceReviewed"]


def test_audit_video_writes_redacted_capture_log(tmp_path, monkeypatch):
    monkeypatch.setenv("DISCLOSURELENS_LOG_DIR", str(tmp_path))

    response = client.post("/audit/video", json=sample_payload())

    assert response.status_code == 200
    log_file = tmp_path / "audit_requests.jsonl"
    assert log_file.exists()
    line = log_file.read_text(encoding="utf-8").strip()

    assert "Future Stories Lab" in line
    assert "screenshotBase64" not in line
    assert "screenshotBytes" in line
    assert "response" in line

    record = json.loads(line)
    assert record["request"]["screenshotBytes"] > 0
    assert record["response"]["riskLabel"] in ["Low", "Medium", "High"]
    assert record["response"]["markdown"].startswith("## DisclosureLens Video Audit")
